const $ = s => document.querySelector(s);
const app = document.getElementById('app');
const KEY='nova_v1';
const DEFAULT={messages:[],topics:{},tts:true,difficulty:'normal',current:null,mastery:null,tab:'chat'};
let state=load();
let listening=false, recognition=null, loading=false;

const lessons={
 normal:{topic:'Bitcoin',answer:'Bitcoin is digitaal geld zonder bank in het midden. In plaats van één partij die bijhoudt wie wat heeft, houdt een wereldwijd netwerk van computers samen één gedeeld kasboek bij: de blockchain. Als jij bitcoin verstuurt, controleert het netwerk of je het echt bezit en wordt de transactie in een nieuw blok vastgelegd.',points:['Geen bank: een netwerk controleert samen','Transacties worden gebundeld in blokken','Elk blok verwijst naar het vorige','Er komen nooit meer dan 21 miljoen bitcoin'],analogy:'Stel je een schrift voor dat iedereen tegelijk bijhoudt. Als iemand stiekem één regel verandert, klopt zijn schrift niet meer met alle andere kopieën.',visual:'flow',nodes:[['Wallet A','ondertekent transactie'],['Netwerk','controleert saldo'],['Nieuw blok','legt transactie vast'],['Wallet B','ontvangt bitcoin']],question:'Iemand verandert een oude transactie in blok 500. Waarom valt dat op en is het zo moeilijk om daarmee weg te komen?',expected:['blok','vorige','hash','keten','netwerk','kopie','rekenkracht']},
 simpler:{topic:'Bitcoin',answer:'Super simpel: Bitcoin is internetgeld. Er is geen bank. Heel veel computers houden samen hetzelfde lijstje bij van wie hoeveel heeft. Omdat al die computers een kopie hebben, kan één persoon het lijstje niet zomaar veranderen.',points:['Internetgeld','Geen bank','Veel computers hebben hetzelfde lijstje','Een geheime sleutel bewijst wat van jou is'],analogy:'Denk aan een groepsapp waarin iedereen dezelfde berichten ziet. Jij kunt een oud bericht niet stiekem bij alle anderen veranderen.',visual:'cards',nodes:[['💰 Geld','digitaal'],['🌍 Netwerk','houdt lijst bij'],['🔑 Sleutel','bewijst eigendom'],['🧱 Blokken','bewaren geschiedenis']],question:'Waarom heb je bij Bitcoin geen bank nodig?',expected:['computers','netwerk','samen','lijst','kasboek']},
 deeper:{topic:'Bitcoin',answer:'Dieper: Bitcoin lost het double-spend-probleem op zonder vertrouwde tussenpartij. Miners gebruiken Proof-of-Work om blokken toe te voegen. Elk blok bevat de hash van het vorige blok. Wie geschiedenis wil herschrijven moet het gewijzigde blok én alle opvolgende Proof-of-Work opnieuw maken en ondertussen het eerlijke netwerk inhalen.',points:['Proof-of-Work beschermt de geschiedenis','Hashes koppelen de blokken','De zwaarste geldige keten wordt gevolgd','Meer bevestigingen maken herschrijven duurder'],analogy:'Het is alsof iedere nieuwe pagina van een kasboek met een extreem dure verzegeling ook de verzegeling van de vorige pagina bevat.',visual:'flow',nodes:[['Blokheader','vorige hash + data'],['SHA-256','digitale vingerafdruk'],['Proof-of-Work','zoek geldige nonce'],['Consensus','netwerk volgt keten']],question:'Waarom maakt elke extra bevestiging een double-spend-aanval duurder?',expected:['rekenkracht','werk','opnieuw','blokken','keten','inhalen']},
 different:{topic:'Bitcoin',answer:'Zie Bitcoin als een glazen kluis op een dorpsplein. Iedereen mag zien welke vakjes waarde verplaatsen, maar alleen de eigenaar heeft de sleutel om zijn vakje te openen. Om de paar minuten wordt een nieuwe, verzegelde laag toegevoegd. Oude lagen aanpassen wordt daardoor steeds lastiger.',points:['Openbaar kasboek','Privésleutel is jouw handtekening','Nieuwe blokken verzegelen geschiedenis','Geen centrale beheerder nodig'],analogy:'Een glazen kluis waarop steeds nieuwe verzegelde lagen worden gestapeld.',visual:'chain',nodes:[['Blok 1','start'],['Blok 2','verwijst naar 1'],['Blok 3','verwijst naar 2'],['Blok 4','verwijst naar 3']],question:'Waarom wordt een oude Bitcoin-transactie veiliger als er meer blokken achter komen?',expected:['blokken','opnieuw','keten','hash','rekenkracht']},
 path:{topic:'Bitcoin',answer:'We maken er een leerroute van. Begin bij wat geld is, daarna het gedeelde kasboek, vervolgens sleutels, mining en schaarste. Tik een stap aan en stel daar meteen een vraag over.',points:['1. Wat is geld?','2. Wat is een gedeeld kasboek?','3. Hoe werken privésleutels?','4. Wat doen miners?','5. Waarom 21 miljoen?'],analogy:'Zoals leren autorijden: eerst besturing begrijpen, daarna pas de motor uit elkaar halen.',visual:'cards',nodes:[['1 · Geld','waarom vertrouwen we het?'],['2 · Kasboek','één geschiedenis'],['3 · Sleutels','eigendom bewijzen'],['4 · Mining','blokken beveiligen'],['5 · Schaarste','21 miljoen']],question:'Waarom kan Bitcoin functioneren zonder centrale bank?',expected:['netwerk','computers','kasboek','samen']}
};

function load(){try{return {...DEFAULT,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return structuredClone(DEFAULT)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function esc(s){return String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function id(){return Math.random().toString(36).slice(2)+Date.now().toString(36)}
function speechSupported(){return !!(window.SpeechRecognition||window.webkitSpeechRecognition)}
function speak(text){if(!state.tts||!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text.replace(/[✅🔁]/g,''));u.lang='nl-NL';u.rate=1.02;speechSynthesis.speak(u)}

function topicTouch(name){if(!state.topics[name])state.topics[name]={name,mastery:0,confidence:10,last:Date.now()};else state.topics[name].last=Date.now();save()}
function addMsg(role,text,lesson=null,kind=''){state.messages.push({id:id(),role,text,lesson,kind});state.messages=state.messages.slice(-60);if(lesson){state.current=lesson;topicTouch(lesson.topic)}save();render();setTimeout(()=>{const e=$('.messages');if(e)e.scrollTop=e.scrollHeight},0)}

async function genericTopic(question){
  const topic=question.replace(/^(wat is|wat zijn|hoe werkt|leg uit|vertel over|what is|how does)\s+/i,'').replace(/[?!.]+$/,'').trim()||'dit onderwerp';
  try{
    const url='https://nl.wikipedia.org/api/rest_v1/page/summary/'+encodeURIComponent(topic);
    const r=await fetch(url,{headers:{accept:'application/json'}});
    if(!r.ok)throw 0; const j=await r.json();
    const text=(j.extract||'').trim(); if(!text)throw 0;
    const sentences=text.split(/(?<=[.!?])\s+/).filter(Boolean);
    const short=sentences.slice(0,3).join(' ');
    const words=[...new Set(topic.toLowerCase().split(/\s+/).concat((short.match(/[A-Za-zÀ-ÿ]{6,}/g)||[]).slice(0,8)))];
    return {topic:j.title||topic,answer:short,points:sentences.slice(0,4).map(x=>x.replace(/\s+/g,' ').slice(0,120)),analogy:'Ik bouw het eerst op vanuit de kern. Vraag “simpeler” of “dieper” als je een andere uitleg wilt.',visual:'cards',nodes:(sentences.slice(0,4).length?sentences.slice(0,4):[short]).map((s,i)=>['Kern '+(i+1),s.slice(0,72)]),question:`Leg in je eigen woorden uit wat ${j.title||topic} is en waarom het belangrijk is.`,expected:words.slice(0,6),source:'Wikipedia'};
  }catch{
    return {topic:topic[0]?.toUpperCase()+topic.slice(1),answer:`Ik heb voor “${topic}” in deze zelfstandige demo nog geen volledige kennisbron. De leerinterface werkt wel helemaal. Probeer “Wat is Bitcoin?” voor de volledige ervaring, of stel een bekend encyclopedisch onderwerp zoals “Wat is zwaartekracht?”`,points:['Ik probeer eerst een publieke kennisbron','Daarna maak ik er een korte uitleg van','De begripsmodus controleert wat jij ervan hebt begrepen'],analogy:'NOVA is hier al het klaslokaal; de onbeperkte AI-motor kan later als extra brein worden aangesloten.',visual:'cards',nodes:[['Vraag','jij kiest onderwerp'],['Uitleg','NOVA vat samen'],['Visual','concepten op bord'],['Test','bewijs begrip']],question:`Wat heb je tot nu toe begrepen over ${topic}?`,expected:topic.toLowerCase().split(/\s+/)};
  }
}

async function ask(text,mode='normal'){
  text=(text||'').trim(); if(!text||loading)return;
  if(state.mastery){return answerMastery(text)}
  addMsg('user',text);
  loading=true;render();
  let lesson;
  const bitcoin=/bitcoin|blockchain|crypto/i.test(text)||state.current?.topic==='Bitcoin'&&mode!=='normal';
  if(bitcoin){lesson=structuredClone(lessons[mode]||lessons.normal)} else {lesson=await genericTopic(text)}
  await new Promise(r=>setTimeout(r,350));
  loading=false; addMsg('nova',lesson.answer,lesson,'answer'); speak(lesson.answer)
}

function startMastery(){if(!state.current)return;state.mastery={question:state.current.question,expected:state.current.expected||[],topic:state.current.topic};save();addMsg('nova','Masterymodus. Eén vraag — antwoord in je eigen woorden:\n\n'+state.mastery.question,null,'mastery');speak(state.mastery.question)}
function answerMastery(text){
  const m=state.mastery;if(!m)return;addMsg('user',text); const a=text.toLowerCase(); const hits=m.expected.filter(k=>a.includes(String(k).toLowerCase())); const words=a.split(/\s+/).filter(Boolean).length; const understood=hits.length>=Math.min(2,m.expected.length)&&words>=6; let t=state.topics[m.topic]||{name:m.topic,mastery:0,confidence:10,last:Date.now()};
  if(understood){t.mastery=Math.min(100,(t.mastery||0)+Math.max(18,Math.min(34,10+hits.length*6)));t.confidence=Math.min(100,(t.confidence||0)+20);t.last=Date.now();state.topics[m.topic]=t;state.mastery=null;save();const msg=`✅ Goed. Je gebruikt ${hits.slice(0,3).join(', ')} en legt het in je eigen woorden uit. Je beheersing van ${m.topic} is nu ${t.mastery}%.`;addMsg('nova',msg);speak(msg)}
  else{t.confidence=Math.max(0,(t.confidence||0)-5);state.topics[m.topic]=t;save();const missing=m.expected.filter(k=>!a.includes(String(k).toLowerCase())).slice(0,3);const msg=`🔁 Nog niet helemaal. Denk vooral aan ${missing.join(', ')||'het mechanisme erachter'}. Bij Bitcoin: als je een oud blok wijzigt verandert de digitale vingerafdruk, waardoor de volgende blokken niet meer aansluiten. Probeer het nog één keer in je eigen woorden.`;addMsg('nova',msg);speak(msg)}
}
function control(mode){if(!state.current)return;if(mode==='simpler')state.difficulty='simpel';if(mode==='deeper')state.difficulty='diep';if(mode==='different'||mode==='learn')state.difficulty='normaal';save();if(mode==='show'){state.tab='board';save();render();return} if(mode==='mastery')return startMastery(); const prompt=mode==='simpler'?`Leg ${state.current.topic} simpeler uit`:mode==='deeper'?`Leg ${state.current.topic} dieper uit`:mode==='different'?`Leg ${state.current.topic} anders uit`:`Leer mij ${state.current.topic}`;ask(prompt,mode==='learn'?'path':mode)}
function reset(){window.speechSynthesis?.cancel?.();state={...DEFAULT,topics:state.topics,tts:state.tts};save();render()}

function startMic(){
  if(!speechSupported()){showNotice('Spraakherkenning wordt hier niet ondersteund. Typ je vraag hieronder.');return}
  if(listening){recognition?.stop();return}
  const SR=window.SpeechRecognition||window.webkitSpeechRecognition;recognition=new SR();recognition.lang='nl-NL';recognition.interimResults=true;recognition.continuous=false;listening=true;render();
  let final=''; recognition.onresult=e=>{let inter='';for(let i=e.resultIndex;i<e.results.length;i++){const t=e.results[i][0].transcript;if(e.results[i].isFinal)final+=t;else inter+=t} const box=$('#homeSpeech');if(box)box.textContent=final+inter||'Ik luister…';const in2=$('#chatInput');if(in2)in2.value=final+inter};recognition.onerror=e=>{listening=false;showNotice(e.error==='not-allowed'?'Microfoon is geblokkeerd. Geef toestemming of typ je vraag.':'Ik kon je niet goed verstaan. Probeer opnieuw.')};recognition.onend=()=>{listening=false;if(final.trim())ask(final.trim());else render()};recognition.start()
}
function showNotice(t){const n=$('#notice');if(n){n.textContent=t;n.classList.remove('hidden');setTimeout(()=>n?.classList.add('hidden'),4500)}else alert(t)}

function renderHome(){app.innerHTML=`<div class="app"><section class="home"><div class="home-inner"><button class="icon-btn" style="position:absolute;right:18px;top:18px" id="tts">${state.tts?'🔊':'🔇'}</button><div class="orb"></div><h1 class="brand">NOVA</h1><p class="tag">Vraag me letterlijk alles. Ik leg het uit totdat jij het begrijpt.</p><p class="sub">Praat alsof je met een slim mens praat — of typ je vraag.</p><button class="mic-big ${listening?'listening':''}" id="mic">🎙️</button><div class="sub" id="homeSpeech">${listening?'Ik luister…':'Tik op de microfoon en praat'}</div><form class="composer" id="homeForm"><input class="input" id="homeInput" placeholder="…of typ je vraag" autocomplete="off"><button class="send">➜</button></form><div id="notice" class="notice hidden"></div><div class="chips"><button class="chip starter">Wat is Bitcoin?</button><button class="chip starter">Wat is zwaartekracht?</button><button class="chip starter">Hoe werkt fotosynthese?</button></div></div></section></div>`;
  $('#mic').onclick=startMic;$('#tts').onclick=()=>{state.tts=!state.tts;save();render()};$('#homeForm').onsubmit=e=>{e.preventDefault();ask($('#homeInput').value)};document.querySelectorAll('.starter').forEach(b=>b.onclick=()=>ask(b.textContent));
}
function renderBoard(l){if(!l)return '<p class="sub">Stel een vraag en het bord komt tot leven.</p>';let core='';if(l.visual==='cards'){core=`<div class="cards">${l.nodes.map(n=>`<div class="card"><b>${esc(n[0])}</b><span class="sub">${esc(n[1])}</span></div>`).join('')}</div>`}else if(l.visual==='chain'){core=`<div class="chain">${l.nodes.map((n,i)=>`${i?'<span class="link"></span>':''}<div class="block"><b>${esc(n[0])}</b><div class="hash">#${(0x9f3a+i*7919).toString(16)}…</div><div class="sub" style="font-size:10px">${esc(n[1])}</div></div>`).join('')}</div>`}else{core=`<div class="flow">${l.nodes.map((n,i)=>`${i?'<div class="arrow">→</div>':''}<div class="node" style="animation-delay:${i*.08}s"><div class="node-num">${i+1}</div><div class="lbl">${esc(n[0])}</div><div class="det">${esc(n[1])}</div></div>`).join('')}</div>`}
  const bitcoin=l.topic==='Bitcoin'?`<div class="chain"><div class="block"><b>Blok 1</b><div class="hash">#9f3a…</div></div><span class="link"></span><div class="block"><b>Blok 2</b><div class="hash">#be29…</div></div><span class="link"></span><div class="block"><b>Blok 3</b><div class="hash">#dd18…</div></div></div>`:'';
  return `<h3 class="visual-title">${esc(l.topic)} zichtbaar gemaakt</h3>${core}${bitcoin}<div class="analogy"><b class="gradient">Analogie · </b>${esc(l.analogy||'')}</div>`
}
function renderBrain(){const ts=Object.values(state.topics);if(!ts.length)return '<p class="sub">Je kenniskaart groeit zodra je iets leert.</p>';const positions=[[50,22],[22,47],[78,47],[35,77],[65,77],[50,50]];return `<div class="brain-map">${ts.slice(0,6).map((t,i)=>{const p=positions[i%positions.length],sz=44+Math.min(34,t.mastery||0)*.45;return `<div class="brain-node" style="left:${p[0]}%;top:${p[1]}%;width:${sz}px;height:${sz}px">${esc(t.name)}</div>`}).join('')}</div>${ts.filter(t=>t.last).map(t=>`<div class="topic-card"><div class="topic-row"><b>${esc(t.name)}</b><span class="mastery">${t.mastery||0}%</span></div><div class="bar"><span style="width:${t.mastery||0}%"></span></div><div class="mini"><span>Zekerheid ${t.confidence||0}%</span><span>${new Date(t.last).toLocaleDateString('nl-NL')}</span></div></div>`).join('')}`}
function renderSession(){const l=state.current;app.innerHTML=`<div class="app"><header class="header"><div class="header-left"><div class="orb small ${loading?'active':''}"></div><div><div class="title gradient">NOVA</div><div class="lesson-meta">${esc(l?.topic||'')} · ${esc(state.difficulty||'normaal')}</div></div></div><div style="display:flex;gap:7px"><button class="icon-btn" id="tts">${state.tts?'🔊':'🔇'}</button><button class="icon-btn" id="reset">↻</button></div></header><div class="actions"><button class="action primary" data-c="mastery">🎯 Laat het me echt begrijpen</button><button class="action" data-c="different">🔀 Leg het anders uit</button><button class="action" data-c="simpler">↓ Simpeler</button><button class="action" data-c="deeper">↑ Dieper</button><button class="action" data-c="show">👁 Laat zien</button><button class="action" data-c="learn">🧭 Leer dit onderwerp</button></div><div class="workspace"><section class="panel chat ${state.tab==='chat'?'active':''}"><div class="messages">${state.messages.map(m=>`<div class="message ${m.role}">${m.role==='nova'?'<div class="orb nova-dot"></div>':''}<div class="bubble">${esc(m.text).replace(/\n/g,'<br>')}${m.lesson&&m.lesson.points?.length?`<ul class="points">${m.lesson.points.map(p=>`<li>${esc(p)}</li>`).join('')}</ul>${m.lesson.source?`<div class="mode-badge">bron: ${esc(m.lesson.source)}</div>`:''}`:''}</div></div>`).join('')}${loading?'<div class="loading"><div class="orb nova-dot active"></div>NOVA denkt <span class="dots"><span></span><span></span><span></span></span></div>':''}</div><div class="chat-bottom">${state.mastery?'<div class="mastery-banner">🎯 Masterymodus actief — leg het in je eigen woorden uit.</div>':''}<form class="composer" id="chatForm"><button type="button" class="icon-btn" id="mic">🎙️</button><input class="input" id="chatInput" placeholder="${state.mastery?'Jouw antwoord…':'Stel een vervolgvraag…'}"><button class="send">➜</button></form><div id="notice" class="notice hidden"></div></div></section><section class="panel board ${state.tab==='board'?'active':''}"><div class="panel-head">Living Board</div><div class="board-body">${renderBoard(l)}</div></section><section class="panel brain ${state.tab==='brain'?'active':''}"><div class="panel-head" style="color:var(--violet)">My Brain</div><div class="brain-body">${renderBrain()}</div></section></div><nav class="mobile-tabs"><button class="mobile-tab ${state.tab==='chat'?'active':''}" data-tab="chat">💬 Gesprek</button><button class="mobile-tab ${state.tab==='board'?'active':''}" data-tab="board">✨ Board</button><button class="mobile-tab ${state.tab==='brain'?'active':''}" data-tab="brain">🧠 My Brain</button></nav></div>`;
  $('#tts').onclick=()=>{state.tts=!state.tts;save();render()};$('#reset').onclick=reset;$('#mic').onclick=startMic;$('#chatForm').onsubmit=e=>{e.preventDefault();ask($('#chatInput').value)};document.querySelectorAll('[data-c]').forEach(b=>b.onclick=()=>control(b.dataset.c));document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;save();render()})
}
function render(){if(!state.messages.length)renderHome();else renderSession()}
render();
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
